# Generated by Django 5.1.5 on 2025-03-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportformation',
            name='date_debut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rapportformation',
            name='date_fin',
            field=models.DateField(),
        ),
    ]
