# Generated by Django 5.1.5 on 2025-03-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApps', '0002_alter_rapportformation_date_debut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportformation',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rapportformation',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
