# Generated by Django 5.1.5 on 2025-03-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApps', '0003_alter_rapportformation_date_debut_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetailsObjectifsRapport',
        ),
    ]
