# Generated by Django 5.1.5 on 2025-03-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApps', '0004_delete_detailsobjectifsrapport'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportformation',
            name='lieu',
            field=models.CharField(default='abidjan', max_length=220),
        ),
    ]
