# Generated by Django 5.1.5 on 2025-03-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApps', '0005_rapportformation_lieu'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportformation',
            name='img_formation',
            field=models.FileField(blank=True, default='doc_img_formation/img.png', null=True, upload_to='doc_img_formation/'),
        ),
        migrations.AlterField(
            model_name='rapportformation',
            name='pdf_recapitulatif',
            field=models.FileField(blank=True, null=True, upload_to='doc_pdf/'),
        ),
    ]
